trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Install Node.js for frontend
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install frontend dependencies and build
- script: |
    cd frontend-Next
    npm install
    npm run build
  displayName: 'Build Frontend'

# Step 3: Install Java 17 from AdoptOpenJDK
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17.x'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AdoptOpenJDK' # Download Java 17 from AdoptOpenJDK
  displayName: 'Install Java 17'

# Step 4: Run backend tests and build
- script: |
    cd ../backend-BootStrap
    ./mvnw clean test
    ./mvnw clean install
  displayName: 'Run Backend Tests and Build'

# Step 5: Publish backend test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Backend Test Results'

# Step 6: Copy Backend Artifacts
- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)/backend'
  displayName: 'Copy Backend Artifacts'

# Step 7: Copy Frontend Artifacts
- task: CopyFiles@2
  inputs:
    contents: '**/frontend-Next/out/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
  displayName: 'Copy Frontend Artifacts'

# Step 8: Publish Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
