trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  displayName: 'Install Java 17'
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Step 3: Install Node.js for frontend
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 4: Install frontend dependencies and build
- script: |
    cd frontend-Next
    npm install
    npm run build
  displayName: 'Build Frontend'

# Step 5: Run backend tests and build
- script: |
    cd backend-BootStrap
    ./mvnw clean test
    ./mvnw clean install
  displayName: 'Run Backend Tests and Build'
  continueOnError: true  # Continue pipeline even if tests fail
